qcacld-3.0: Mark hdd_display_stats_help as `__maybe_unused`
This fixes the below warning

../drivers/staging/qcacld-3.0/core/hdd/src/wlan_hdd_wext.c:3238:13: error: 'hdd_display_stats_help' defined but not used [-Werror=unused-function]
 3238 | static void hdd_display_stats_help(void)

Signed-off-by: Cyber Knight <cyberknight755@gmail.com>
(cherry picked from commit ab2b39eff19132922110de2dda3e459d7f967267)
Signed-off-by: Richard Raya <rdxzv.dev@gmail.com>